export const IS_LOADING = "IS_LOADING";
export const IS_ERROR = "IS_ERROR";

export const GET_HOMEPAGE_DATA = "GET_HOMEPAGE_DATA";

// get movies by language
export const GET_MOVIES_BY_LANGUAGE_LOADING = "GET_MOVIES_BY_LANGUAGE_LOADING";
export const GET_MOVIES_BY_LANGUAGE_SUCCESS = "GET_MOVIES_BY_LANGUAGE_SUCCESS";
export const GET_MOVIES_BY_LANGUAGE_ERROR = "GET_MOVIES_BY_LANGUAGE_ERROR";

// get categories
export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

// get movies by category
export const GET_MOVIES_BY_CATEGORY_LOADING = "GET_MOVIES_BY_CATEGORY_LOADING";
export const GET_MOVIES_BY_CATEGORY_SUCCESS = "GET_MOVIES_BY_CATEGORY_SUCCESS";
export const GET_MOVIES_BY_CATEGORY_ERROR = "GET_MOVIES_BY_CATEGORY_ERROR";

// get movie detail
export const GET_MOVIE_DETAIL_LOADING = "GET_MOVIE_DETAIL_LOADING";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_ERROR = "GET_MOVIE_DETAIL_ERROR";

//search input
export const SEARCH_INPUT_SUCCESS = "SEARCH_INPUT_SUCCESS";

export const GET_SUBSCRIBERS_SUCCESS = "GET_EPISODE_SUCCESS";

// get movies
export const GET_MOVIES_LOADING = "GET_MOVIES_LOADING";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

// get movies
export const GET_SUBSCRIPTION_PLANS_LOADING = "GET_SUBSCRIPTION_PLANS_LOADING";
export const GET_SUBSCRIPTION_PLANS_SUCCESS = "GET_SUBSCRIPTION_PLANS_SUCCESS";
export const GET_SUBSCRIPTION_PLANS_ERROR = "GET_SUBSCRIPTION_PLANS_ERROR";

// get movies
export const GET_MONTHLY_SUB_LOADING = "GET_MONTHLY_SUB_LOADING";
export const GET_MONTHLY_SUB_SUCCESS = "GET_MONTHLY_SUB_SUCCESS";
export const GET_MONTHLY_SUB_ERROR = "GET_MONTHLY_SUB_ERROR";

// get movies
export const GET_SUB_LOADING = "GET_SUB_LOADING";
export const GET_SUB_SUCCESS = "GET_SUB_SUCCESS";
export const GET_SUB_ERROR = "GET_SUB_ERROR";

// get movies
export const GET_USER_SUB_LOADING = "GET_USER_SUB_LOADING";
export const GET_USER_SUB_SUCCESS = "GET_USER_SUB_SUCCESS";
export const GET_USER_SUB_ERROR = "GET_USER_SUB_ERROR";

// get movies
export const CREATE_SUBSCRIPTION_LOADING = "CREATE_SUBSCRIPTION_LOADING";
export const CREATE_SUBSCRIPTION_SUCCESS = "CREATE_SUBSCRIPTION_SUCCESS";
export const CREATE_SUBSCRIPTION_ERROR = "CREATE_SUBSCRIPTION_ERROR";

// get movies
export const CREATE_RENTAL_LOADING = "CREATE_RENTAL_LOADING";
export const CREATE_RENTAL_SUCCESS = "CREATE_RENTAL_SUCCESS";
export const CREATE_RENTAL_ERROR = "CREATE_RENTAL_ERROR";

// get movies
export const GET_RENTAL_SUCCESS = "GET_RENTAL_SUCCESS";
export const GET_RENTAL_ERROR = "GET_RENTAL_ERROR";

// get movies
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_ERROR = "GET_LANGUAGES_ERROR";

// get movies
export const SAVE_VIEW_COUNT_SUCCESS = "SAVE_VIEW_COUNT_SUCCESS";
export const SAVE_VIEW_COUNT_ERROR = "SAVE_VIEW_COUNT_ERROR";

// get episdos
export const GET_EPISODE_LOADING = "GET_EPISODE_LOADING";
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";
export const GET_EPISODE_ERROR = "GET_EPISODE_ERROR";

//get SubscribersOne
export const GET_SUBSCRIBERONE_SUCCESS = "GET_SUBSCRIBERONE_SUCCESS";
export const GET_SUBSCRIBERONE_ERROR = "GET_SUBSCRIBERONE_ERROR";
export const GET_SUBSCRIBERONE_LOADING = "GET_SUBSCRIBERONE_LOADING";

// get episdos
export const GET_EPISODE_DETAIL_LOADING = "GET_EPISODE_DETAIL_LOADING";
export const GET_EPISODE_DETAIL_SUCCESS = "GET_EPISODE_DETAIL_SUCCESS";
export const GET_EPISODE_DETAIL_ERROR = "GET_EPISODE_DETAIL_ERROR";

export const RESET_EPISODE_DETAIL = "RESET_EPISODE_DETAIL";
export const RESET_MOVIE_DETAIL = "RESET_MOVIE_DETAIL";

export const GET_RESUME_SESSION_LOADING = "GET_RESUME_SESSION_LOADING";
export const GET_RESUME_SESSION_SUCCESS = "GET_RESUME_SESSION_SUCCESS";
export const GET_RESUME_SESSION_ERROR = "GET_RESUME_SESSION_ERROR";

export const UPDATE_RESUME_SESSION_LOADING = "UPDATE_RESUME_SESSION_LOADING";
export const CREATE_RESUME_SESSION_SUCCESS = "CREATE_RESUME_SESSION_SUCCESS";
export const CREATE_RESUME_SESSION_ERROR = "CREATE_RESUME_SESSION_ERROR";

export const SET_EPISODE_NO = "SET_EPISODE_NO";
